spring:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    username: hospital
    password: hospital
    url: jdbc:h2:mem:doctor_db;
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate


server:
  error:
    include-stacktrace: NEVER